/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Och4bv5UVgr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Baskerville } from 'next/font/google'
import { Prata } from 'next/font/google'

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"

export function Component() {
  return (
    (<div className="grid grid-cols-1 md:grid-cols-[280px_1fr] min-h-screen">
      <div className="hidden border-r bg-gray-100/40 md:block dark:bg-gray-800/40">
        <div className="flex h-full max-h-screen flex-col gap-4 p-6">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold">Cosmetic Finder</h1>
            <Button variant="ghost" size="icon">
              <SearchIcon className="h-5 w-5" />
            </Button>
          </div>
          <div className="flex-1 overflow-auto">
            <nav className="grid gap-2">
              <Link
                href="#"
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                prefetch={false}>
                <PaintbrushIcon className="h-5 w-5" />
                Makeup
              </Link>
              <Link
                href="#"
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                prefetch={false}>
                <SkullIcon className="h-5 w-5" />
                Skincare
              </Link>
              <Link
                href="#"
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                prefetch={false}>
                <HashIcon className="h-5 w-5" />
                Hair
              </Link>
              <Link
                href="#"
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                prefetch={false}>
                <FlowerIcon className="h-5 w-5" />
                Fragrance
              </Link>
              <Link
                href="#"
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                prefetch={false}>
                <BathIcon className="h-5 w-5" />
                Bath & Body
              </Link>
            </nav>
          </div>
          <div className="grid gap-4">
            <Accordion type="single" collapsible>
              <AccordionItem value="filters">
                <AccordionTrigger className="text-base font-semibold">Filters</AccordionTrigger>
                <AccordionContent>
                  <div className="grid gap-4">
                    <div>
                      <h4 className="mb-2 text-sm font-semibold">Price</h4>
                      <div />
                    </div>
                    <div>
                      <h4 className="mb-2 text-sm font-semibold">Ratings</h4>
                      <RadioGroup>
                        <RadioGroupItem value="5" id="rating-5" />
                        <Label htmlFor="rating-5" className="flex items-center gap-2">
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-primary" />
                        </Label>
                        <RadioGroupItem value="4" id="rating-4" />
                        <Label htmlFor="rating-4" className="flex items-center gap-2">
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-muted stroke-muted-foreground" />
                        </Label>
                        <RadioGroupItem value="3" id="rating-3" />
                        <Label htmlFor="rating-3" className="flex items-center gap-2">
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-primary" />
                          <StarIcon className="h-5 w-5 fill-muted stroke-muted-foreground" />
                          <StarIcon className="h-5 w-5 fill-muted stroke-muted-foreground" />
                        </Label>
                      </RadioGroup>
                    </div>
                    <div>
                      <h4 className="mb-2 text-sm font-semibold">Skin Type</h4>
                      <Checkbox id="skin-normal" />
                      <Label htmlFor="skin-normal" className="font-normal">
                        Normal
                      </Label>
                      <Checkbox id="skin-dry" />
                      <Label htmlFor="skin-dry" className="font-normal">
                        Dry
                      </Label>
                      <Checkbox id="skin-oily" />
                      <Label htmlFor="skin-oily" className="font-normal">
                        Oily
                      </Label>
                      <Checkbox id="skin-sensitive" />
                      <Label htmlFor="skin-sensitive" className="font-normal">
                        Sensitive
                      </Label>
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </div>
      </div>
      <div className="flex flex-col">
        <header
          className="flex h-14 items-center gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40">
          <Link href="#" className="md:hidden" prefetch={false}>
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle sidebar</span>
          </Link>
          <div className="flex-1">
            <form>
              <div className="relative">
                <SearchIcon
                  className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
                <Input
                  type="search"
                  placeholder="Search cosmetics..."
                  className="w-full bg-white shadow-none appearance-none pl-8 md:w-2/3 lg:w-1/3 dark:bg-gray-950" />
              </div>
            </form>
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800">
                <img
                  src="/placeholder.svg"
                  width="32"
                  height="32"
                  className="rounded-full"
                  alt="Avatar" />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </header>
        <main className="flex-1 overflow-auto p-4 md:p-6">
          <div className="grid gap-8">
            <div>
              <h2 className="text-2xl font-bold">Popular Makeup</h2>
              <div
                className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-6">
                <div className="bg-white rounded-lg shadow-sm dark:bg-gray-950">
                  <img
                    src="/placeholder.svg"
                    alt="Product Image"
                    width={300}
                    height={300}
                    className="w-full h-48 object-cover rounded-t-lg" />
                  <div className="p-4">
                    <h3 className="text-lg font-semibold">Luminous Foundation</h3>
                    <div className="flex items-center gap-2 mt-2">
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      <span className="text-sm text-gray-500 dark:text-gray-400">(4.2)</span>
                    </div>
                    <p className="text-gray-500 dark:text-gray-400 mt-2 line-clamp-2">
                      Lightweight, buildable coverage for a natural, radiant finish.
                    </p>
                    <div className="flex items-center justify-between mt-4">
                      <span className="text-lg font-semibold">$35</span>
                      <Button size="sm">Add to Cart</Button>
                    </div>
                  </div>
                </div>
                <div className="bg-white rounded-lg shadow-sm dark:bg-gray-950">
                  <img
                    src="/placeholder.svg"
                    alt="Product Image"
                    width={300}
                    height={300}
                    className="w-full h-48 object-cover rounded-t-lg" />
                  <div className="p-4">
                    <h3 className="text-lg font-semibold">Velvet Matte Lipstick</h3>
                    <div className="flex items-center gap-2 mt-2">
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      <span className="text-sm text-gray-500 dark:text-gray-400">(4.7)</span>
                    </div>
                    <p className="text-gray-500 dark:text-gray-400 mt-2 line-clamp-2">
                      Long-lasting, pigment-rich lipstick with a velvety matte finish.
                    </p>
                    <div className="flex items-center justify-between mt-4">
                      <span className="text-lg font-semibold">$24</span>
                      <Button size="sm">Add to Cart</Button>
                    </div>
                  </div>
                </div>
                <div className="bg-white rounded-lg shadow-sm dark:bg-gray-950">
                  <img
                    src="/placeholder.svg"
                    alt="Product Image"
                    width={300}
                    height={300}
                    className="w-full h-48 object-cover rounded-t-lg" />
                  <div className="p-4">
                    <h3 className="text-lg font-semibold">Eyeshadow Palette</h3>
                    <div className="flex items-center gap-2 mt-2">
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      <span className="text-sm text-gray-500 dark:text-gray-400">(3.8)</span>
                    </div>
                    <p className="text-gray-500 dark:text-gray-400 mt-2 line-clamp-2">
                      Highly pigmented eyeshadows in a variety of shimmery and matte shades.
                    </p>
                    <div className="flex items-center justify-between mt-4">
                      <span className="text-lg font-semibold">$45</span>
                      <Button size="sm">Add to Cart</Button>
                    </div>
                  </div>
                </div>
                <div className="bg-white rounded-lg shadow-sm dark:bg-gray-950">
                  <img
                    src="/placeholder.svg"
                    alt="Product Image"
                    width={300}
                    height={300}
                    className="w-full h-48 object-cover rounded-t-lg" />
                  <div className="p-4">
                    <h3 className="text-lg font-semibold">Volumizing Mascara</h3>
                    <div className="flex items-center gap-2 mt-2">
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      <span className="text-sm text-gray-500 dark:text-gray-400">(4.5)</span>
                    </div>
                    <p className="text-gray-500 dark:text-gray-400 mt-2 line-clamp-2">
                      Lengthens and thickens lashes for a bold, dramatic look.
                    </p>
                    <div className="flex items-center justify-between mt-4">
                      <span className="text-lg font-semibold">$20</span>
                      <Button size="sm">Add to Cart</Button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>)
  );
}

function BathIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M9 6 6.5 3.5a1.5 1.5 0 0 0-1-.5C4.683 3 4 3.683 4 4.5V17a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5" />
      <line x1="10" x2="8" y1="5" y2="7" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <line x1="7" x2="7" y1="19" y2="21" />
      <line x1="17" x2="17" y1="19" y2="21" />
    </svg>)
  );
}


function FlowerIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="3" />
      <path
        d="M12 16.5A4.5 4.5 0 1 1 7.5 12 4.5 4.5 0 1 1 12 7.5a4.5 4.5 0 1 1 4.5 4.5 4.5 4.5 0 1 1-4.5 4.5" />
      <path d="M12 7.5V9" />
      <path d="M7.5 12H9" />
      <path d="M16.5 12H15" />
      <path d="M12 16.5V15" />
      <path d="m8 8 1.88 1.88" />
      <path d="M14.12 9.88 16 8" />
      <path d="m8 16 1.88-1.88" />
      <path d="M14.12 14.12 16 16" />
    </svg>)
  );
}


function HashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="9" y2="9" />
      <line x1="4" x2="20" y1="15" y2="15" />
      <line x1="10" x2="8" y1="3" y2="21" />
      <line x1="16" x2="14" y1="3" y2="21" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function PaintbrushIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M18.37 2.63 14 7l-1.59-1.59a2 2 0 0 0-2.82 0L8 7l9 9 1.59-1.59a2 2 0 0 0 0-2.82L17 10l4.37-4.37a2.12 2.12 0 1 0-3-3Z" />
      <path d="M9 8c-2 3-4 3.5-7 4l8 10c2-1 6-5 6-7" />
      <path d="M14.5 17.5 4.5 15" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function SkullIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="9" cy="12" r="1" />
      <circle cx="15" cy="12" r="1" />
      <path d="M8 20v2h8v-2" />
      <path d="m12.5 17-.5-1-.5 1h1z" />
      <path d="M16 20a2 2 0 0 0 1.56-3.25 8 8 0 1 0-11.12 0A2 2 0 0 0 8 20" />
    </svg>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
